services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
      # without this volume the node_modules directory would be overwritten
      # by the mounting of the host directory at runtime
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true